[package]
name = "dot_installer"
version = "0.1.0"
authors = ["Jesse Malinosky <jesse@malinoskj2.dev>"]
edition = "2018"
description = "easily source and install dotfiles"

[lib]
name="lib_dot_installer"
path = "src/linker.rs"

[[bin]]
name = "dot_installer"
path = "src/main.rs"

[dependencies]

structopt = "0.2"
walkdir = "2"

serde = "1.0.89"
serde_derive = "1.0.89"
serde_yaml = "0.8.8"

symlink = "0.1.0"
